### ISSUE TITLE
Memory Leak: performCleanupOnOldImages 

### ISSUE THREAD

**Issue by MoralAlberto** [imojiengineering/imoji-ios-sdk#14]
Hello!

I'm developing an app with your SDK and I've just noticed using Instruments a big memory leak in the next method:

<img width="920" alt="" src="https://cloud.githubusercontent.com/assets/931211/12208148/308ecfce-b64b-11e5-8eed-be685d258af3.png">

<img width="916" alt="" src="https://cloud.githubusercontent.com/assets/931211/12208165/55a06ab6-b64b-11e5-9cf6-20b716743022.png">

I only call the ```getImojiCategoriesWithClassification(.Generic)``` or ```getImojiCategoriesWithClassification(.Trending)```. I commented the line of the method who calls ```performCleanupOnOldImages``` and (obviously) the memory leaks have disappeared.

any idea how to solve this huge memory leak?

thanks in advance

**Comment by nkhoshini** [comment]
Hi @MoralAlberto, we've since removed the manual caching of images in f0f0e6b in favor of NSURLCache. The latest version removes IMMutableImojiSessionStoragePolicy entirely.

Upgrading for you should be quite straightforward. The only notable change is the signature to IMImojiSessionResultSetResponseCallback that'll require small updates on your end.

Thanks!

**Comment by MoralAlberto** [comment]
Thanks! I was using an old SDK's version
